version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  bookingmanagement:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://Cluster76516:WGtse3VmfVZx@cluster76516.zzq9k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster76516